# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-26 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import pages.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_share_additional_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='share',
            name='meta',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='META-\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b'),
        ),
        migrations.AddField(
            model_name='share',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='share',
            name='slug',
            field=models.SlugField(blank=True, help_text='\u041a \u043f\u0440\u0438\u043c\u0435\u0440\u0443, "my_new_awesome_hall"', max_length=150, null=True, validators=[pages.validators.validate_slug_field], verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0441\u044b\u043b\u043a\u0438 \u043a \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435 \u0441\u0430\u0443\u043d\u044b'),
        ),
    ]
