# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-26 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shares', '0003_auto_20171227_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0432\u043e \u0432\u043a\u043b\u0430\u0434\u043a\u0435', max_length=100, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('meta', models.TextField(blank=True, max_length=300, null=True, verbose_name='META-\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b')),
            ],
            options={
                'db_table': 'data_business_page',
                'verbose_name': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 "\u0411\u0438\u0437\u043d\u0435\u0441"',
                'verbose_name_plural': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 "\u0411\u0438\u0437\u043d\u0435\u0441"',
            },
        ),
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0432\u043e \u0432\u043a\u043b\u0430\u0434\u043a\u0435', max_length=100, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('meta', models.TextField(blank=True, max_length=300, null=True, verbose_name='META-\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b')),
                ('map', models.TextField(blank=True, default=b'<iframe class="map__item"  src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d8966.279574741344!2d37.726095!3d55.818067!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46b53450cf0645b9%3A0x869f26e9d7ad24d3!2z0JjQstCw0L3RgtC10LXQstGB0LrQsNGPINGD0LsuLCAxM9C6MSwg0JzQvtGB0LrQstCwLCDQoNC-0YHRgdC40Y8sIDEwNzE1MA!5e0!3m2!1sru!2sru!4v1490693223242" frameborder="0" allowfullscreen></iframe>', help_text='\u041a\u0430\u0440\u0442\u0430, \u043a\u043e\u0442\u043e\u0440\u0430\u044f \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0435\u0442\u0441\u044f \u0432 \u043a\u043e\u043d\u0442\u0430\u043a\u0442\u0430\u0445', max_length=2048, null=True, verbose_name='\u041e\u043a\u043d\u043e \u0441 \u043a\u0430\u0440\u0442\u043e\u0439')),
            ],
            options={
                'db_table': 'data_contacts_page',
                'verbose_name': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 "\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b"',
                'verbose_name_plural': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 "\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b"',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0432\u043e \u0432\u043a\u043b\u0430\u0434\u043a\u0435', max_length=100, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('meta', models.TextField(blank=True, max_length=300, null=True, verbose_name='META-\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b')),
            ],
            options={
                'db_table': 'data_home_page',
                'verbose_name': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 "\u0413\u043b\u0430\u0432\u043d\u0430\u044f"',
                'verbose_name_plural': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 "\u0413\u043b\u0430\u0432\u043d\u0430\u044f"',
            },
        ),
        migrations.CreateModel(
            name='MediaPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0432\u043e \u0432\u043a\u043b\u0430\u0434\u043a\u0435', max_length=100, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('meta', models.TextField(blank=True, max_length=300, null=True, verbose_name='META-\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b')),
            ],
            options={
                'db_table': 'data_Media_page',
                'verbose_name': '\u0421\u0442\u0430\u043d\u0438\u0446\u0430 "\u0412\u0438\u0434\u0435\u043e"',
                'verbose_name_plural': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 "\u0412\u0438\u0434\u0435\u043e"',
            },
        ),
        migrations.CreateModel(
            name='RegistrationPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0432\u043e \u0432\u043a\u043b\u0430\u0434\u043a\u0435', max_length=100, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('meta', models.TextField(blank=True, max_length=300, null=True, verbose_name='META-\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b')),
                ('phone_from', models.CharField(blank=True, default=b'+79651581481', max_length=20, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d \u0434\u043b\u044f \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438 \u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0439')),
                ('phones_to', models.TextField(blank=True, default=b'+79651581481', help_text=b'\xd0\xa3\xd0\xba\xd0\xb0\xd0\xb7\xd1\x8b\xd0\xb2\xd0\xb0\xd0\xb9\xd1\x82\xd0\xb5 \xd1\x82\xd0\xb5\xd0\xbb\xd0\xb5\xd1\x84\xd0\xbe\xd0\xbd\xd1\x8b \xd1\x87\xd0\xb5\xd1\x80\xd0\xb5\xd0\xb7 \xd0\xb7\xd0\xb0\xd0\xbf\xd1\x8f\xd1\x82\xd1\x83\xd1\x8e +7000999222,+7222111333', max_length=1000, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d\u044b \u0434\u043b\u044f \u043e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u044f \u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0439')),
                ('message', models.TextField(blank=True, default=b'\xd0\x9f\xd0\xb0\xd0\xbd\xd0\xb5\xd0\xbb\xd1\x8c \xd0\xb0\xd0\xb4\xd0\xbc\xd0\xb8\xd0\xbd\xd0\xb8\xd1\x81\xd1\x82\xd1\x80\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f \xd0\xbf\xd0\xbe\xd0\xbf\xd0\xbe\xd0\xbb\xd0\xbd\xd0\xb8\xd0\xbb\xd0\xb0\xd1\x81\xd1\x8c \xd0\xbd\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xbc \xd0\xba\xd0\xbe\xd0\xbd\xd1\x81\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd0\xb0\xd0\xbd\xd0\xbe\xd0\xbc!', help_text=b'<div class="variablesHint">\xd0\x94\xd0\xbe\xd1\x81\xd1\x82\xd1\x83\xd0\xbf\xd0\xbd\xd1\x8b\xd0\xb5 \xd0\xbf\xd0\xb5\xd1\x80\xd0\xb5\xd0\xbc\xd0\xb5\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb5:<br/><br/><span class="variable">{{first_name}}</span> &mdash; <span class="helpText">\xd0\x98\xd0\xb2\xd0\xb0\xd0\xbd</span><br/><span class="variable">{{last_name}}</span> &mdash; <span class="helpText">\xd0\x98\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xbe\xd0\xb2\xd0\xb8\xd1\x87</span><br/><span class="variable">{{middle_name}}</span> &mdash; <span class="helpText">\xd0\x98\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xbe\xd0\xb2</span><br/><span class="variable">{{full_name}}</span> &mdash; <span class="helpText">\xd0\x98\xd0\xb2\xd0\xb0\xd0\xbd \xd0\x98\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xbe\xd0\xb2\xd0\xb8\xd1\x87</span><br/><span class="variable">{{status}}</span> &mdash; <span class="helpText">\xd0\x97\xd0\xb0\xd1\x80\xd0\xb5\xd0\xb3\xd0\xb8\xd1\x81\xd1\x82\xd1\x80\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb9 "\xd0\x90"/\xd0\x9d\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb9</span><br/><span class="variable">{{site}}</span> &mdash; <span class="helpText">cosmeticsyou.ru.</span><br/><div>', max_length=1000, null=True, verbose_name='\u041e\u043f\u0446\u0438\u043e\u043d\u0430\u043b\u044c\u043d\u043e\u0435 \u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435')),
            ],
            options={
                'db_table': 'data_registration_page',
                'verbose_name': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 "\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u044f"',
                'verbose_name_plural': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 "\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u044f"',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(default=b'\xd0\x93\xd0\xbb\xd0\xbe\xd0\xb1\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd0\xb0\xd1\x8f \xd0\xbd\xd0\xb0\xd1\x81\xd1\x82\xd1\x80\xd0\xbe\xd0\xb9\xd0\xba\xd0\xb0', max_length=100, verbose_name='\u0418\u043c\u044f \u043d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438')),
                ('widgets', models.TextField(blank=True, max_length=8196, null=True, verbose_name='\u041c\u0435\u0442\u0440\u0438\u043a\u0438, \u0432\u0438\u0434\u0436\u0435\u0442\u044b \u0438 \u043f\u0440\u043e\u0447\u0435\u0435')),
                ('meta', models.TextField(blank=True, max_length=300, null=True, verbose_name='\u0413\u043b\u043e\u0431\u0430\u043b\u044c\u043d\u043e\u0435 META-\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0441\u0430\u0439\u0442\u0430')),
                ('email', models.CharField(blank=True, default=b'support@cosmeticsyou.ru', max_length=200, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default=b'+7 (965) 158-14-81', max_length=90, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('city', models.CharField(blank=True, default=b'\xd0\xb3. \xd0\x9c\xd0\xbe\xd1\x81\xd0\xba\xd0\xb2\xd0\xb0', max_length=100, null=True, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('address', models.CharField(blank=True, default=b'\xd0\x98\xd0\xb2\xd0\xb0\xd0\xbd\xd1\x82\xd0\xb5\xd0\xb5\xd0\xb2\xd1\x81\xd0\xba\xd0\xb0\xd1\x8f \xd0\xb4. 13 \xd0\xba\xd0\xbe\xd1\x80.1', max_length=200, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('addressHref', models.CharField(blank=True, default=b'https://www.google.ru/maps/place/Ivanteevskaya+ul.,+13%D0%BA1,+Moskva,+107150/@55.818067,37.7239063,17z/data=!3m1!4b1!4m5!3m4!1s0x46b53450cf0645b9:0x869f26e9d7ad24d3!8m2!3d55.818067!4d37.726095?sa=X&ved=0ahUKEwi_jtfNru3SAhWkE5oKHSiQDNYQ8gEIHjAA', max_length=500, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043f\u0435\u0440\u0435\u043d\u0430\u043f\u0440\u0430\u0432\u043b\u044f\u044e\u0449\u0430\u044f \u043d\u0430 \u043a\u0430\u0440\u0442\u044b(Google/Yandex)')),
            ],
            options={
                'db_table': 'site_settings',
                'verbose_name': '\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0430',
                'verbose_name_plural': '\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='SharesPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, help_text='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0432\u043e \u0432\u043a\u043b\u0430\u0434\u043a\u0435', max_length=100, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('meta', models.TextField(blank=True, max_length=300, null=True, verbose_name='META-\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b')),
                ('shares', models.ManyToManyField(blank=True, help_text='\u0410\u043a\u0446\u0438\u0438, \u043a\u043e\u0442\u043e\u0440\u044b\u0435 \u0431\u0443\u0434\u0443\u0442 \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c\u0441\u044f \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435 "\u0410\u043a\u0446\u0438\u0438".', related_name='shown_prices_sauna', to='shares.Share', verbose_name='\u0410\u043a\u0446\u0438\u0438')),
            ],
            options={
                'db_table': 'data_prices_page',
                'verbose_name': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 "\u0410\u043a\u0446\u0438\u0438"',
                'verbose_name_plural': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 "\u0410\u043a\u0446\u0438\u0438"',
            },
        ),
    ]
