# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesspage',
            old_name='title',
            new_name='page_title',
        ),
        migrations.RenameField(
            model_name='contactspage',
            old_name='title',
            new_name='page_title',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='title',
            new_name='page_title',
        ),
        migrations.RenameField(
            model_name='mediapage',
            old_name='title',
            new_name='page_title',
        ),
        migrations.RenameField(
            model_name='registrationpage',
            old_name='title',
            new_name='page_title',
        ),
        migrations.RenameField(
            model_name='sharespage',
            old_name='title',
            new_name='page_title',
        ),
    ]
