# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-20 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20180118_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationpage',
            name='account_sid',
            field=models.CharField(blank=True, default=b'', help_text=b'Account Sid \xd0\xb8\xd0\xb7 \xd0\xb0\xd0\xba\xd0\xba\xd0\xb0\xd1\x83\xd0\xbd\xd1\x82\xd0\xb0 TwilioAPI', max_length=350, null=True, verbose_name='Account Sid'),
        ),
        migrations.AddField(
            model_name='registrationpage',
            name='auth_token',
            field=models.CharField(blank=True, default=b'', help_text=b'Auth Token \xd0\xb8\xd0\xb7 \xd0\xb0\xd0\xba\xd0\xba\xd0\xb0\xd1\x83\xd0\xbd\xd1\x82\xd0\xb0 TwilioAPI', max_length=350, null=True, verbose_name='Auth Token'),
        ),
        migrations.AlterField(
            model_name='registrationpage',
            name='phone_from',
            field=models.CharField(blank=True, default=b'+17609068017', max_length=20, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d \u0434\u043b\u044f \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438 \u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0439'),
        ),
        migrations.AlterField(
            model_name='registrationpage',
            name='phones_to',
            field=models.TextField(blank=True, default=b'+79859051251', help_text=b'\xd0\xa3\xd0\xba\xd0\xb0\xd0\xb7\xd1\x8b\xd0\xb2\xd0\xb0\xd0\xb9\xd1\x82\xd0\xb5 \xd1\x82\xd0\xb5\xd0\xbb\xd0\xb5\xd1\x84\xd0\xbe\xd0\xbd\xd1\x8b \xd1\x87\xd0\xb5\xd1\x80\xd0\xb5\xd0\xb7 \xd0\xb7\xd0\xb0\xd0\xbf\xd1\x8f\xd1\x82\xd1\x83\xd1\x8e +7000999222,+7222111333', max_length=1000, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d\u044b \u0434\u043b\u044f \u043e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u044f \u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0439'),
        ),
    ]
