# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [(b'accounts', '0001_initial'), (b'accounts', '0002_auto_20170828_1424'), (b'accounts', '0003_auto_20171122_1308'), (b'accounts', '0004_relatedconsultanttablerelations_empty_middle_name')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=36, verbose_name=b'\xd0\xa4\xd0\xb0\xd0\xbc\xd0\xb8\xd0\xbb\xd0\xb8\xd1\x8f')),
                ('first_name', models.CharField(max_length=32, verbose_name=b'\xd0\x98\xd0\xbc\xd1\x8f')),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True, verbose_name=b'\xd0\x9e\xd1\x82\xd1\x87\xd0\xb5\xd1\x81\xd1\x82\xd0\xb2\xd0\xbe')),
                ('empty_middle_name', models.BooleanField(default=False, verbose_name=b'\xd0\x9d\xd0\xb5\xd1\x82 \xd0\xbe\xd1\x82\xd1\x87\xd0\xb5\xd1\x81\xd1\x82\xd0\xb2\xd0\xb0.')),
                ('birthday', models.DateTimeField(verbose_name=b'\xd0\x94\xd0\xb5\xd0\xbd\xd1\x8c \xd1\x80\xd0\xbe\xd0\xb6\xd0\xb4\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f')),
                ('citizenship', models.BooleanField(default=False, verbose_name=b'\xd0\x9d\xd0\xb5 \xd0\xb3\xd1\x80\xd0\xb0\xd0\xb6\xd0\xb4\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xbd \xd0\xa0\xd0\xa4.')),
                ('passport_data', models.CharField(max_length=26, verbose_name=b'\xd0\xa1\xd0\xb5\xd1\x80\xd0\xb8\xd1\x8f \xd0\xb8 \xd0\xbd\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x80 \xd0\xbf\xd0\xb0\xd1\x81\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82\xd0\xb0')),
                ('phone_number', models.CharField(max_length=26, verbose_name=b'\xd0\x9d\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x80 \xd1\x82\xd0\xb5\xd0\xbb\xd0\xb5\xd1\x84\xd0\xbe\xd0\xbd\xd0\xb0')),
                ('city', models.CharField(max_length=50, verbose_name=b'\xd0\x93\xd0\xbe\xd1\x80\xd0\xbe\xd0\xb4')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xd0\x9e\xd0\xb1\xd0\xbb\xd0\xb0\xd1\x81\xd1\x82\xd1\x8c')),
                ('street', models.CharField(max_length=50, verbose_name=b'\xd0\xa3\xd0\xbb\xd0\xb8\xd1\x86\xd0\xb0')),
                ('num_home', models.CharField(max_length=5, verbose_name=b'\xd0\x94\xd0\xbe\xd0\xbc')),
                ('num_apartment', models.DecimalField(decimal_places=1, max_digits=999, verbose_name=b'\xd0\x9a\xd0\xb2\xd0\xb0\xd1\x80\xd1\x82\xd0\xb8\xd1\x80\xd0\xb0')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name=b'E-mail')),
                ('consultant_num', models.CharField(blank=True, max_length=40, null=True, verbose_name=b'\xd0\x9d\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x80 \xd0\xba\xd0\xbe\xd0\xbd\xd1\x81\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd0\xb0\xd0\xbd\xd1\x82\xd0\xb0')),
                ('status', models.CharField(choices=[('\u041d\u043e\u0432\u044b\u0439', b'\xd0\x9d\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb9'), ('\u0417\u0430\u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0439 \u0410', b'\xd0\x97\xd0\xb0\xd1\x80\xd0\xb5\xd0\xb3\xd0\xb8\xd1\x81\xd1\x82\xd1\x80\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb9 \xd0\x90'), ('\u0417\u0430\u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0439 \u0411', b'\xd0\x97\xd0\xb0\xd1\x80\xd0\xb5\xd0\xb3\xd0\xb8\xd1\x81\xd1\x82\xd1\x80\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb9 \xd0\x91'), ('\u041f\u0443\u0441\u0442\u043e\u0439', b'\xd0\x9f\xd1\x83\xd1\x81\xd1\x82\xd0\xbe\xd0\xb9')], default=b'\xd0\x9d\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb9', max_length=20, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438')),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u0414\u0430\u0442\u0430 \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('refferal_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u0420\u0435\u0444\u0435\u0440\u0430\u043b\u044c\u043d\u0430\u044f \u0441\u0441\u044b\u043b\u043a\u0430')),
                ('url_to_personal_room', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u0432 \u043b\u0438\u0447\u043d\u044b\u0439 \u043a\u0430\u0431\u0438\u043d\u0435\u0442')),
                ('user_lead', models.ManyToManyField(blank=True, related_name='_user_user_lead_+', to=b'accounts.User', verbose_name='\u041f\u0440\u0438\u0433\u043b\u0430\u0448\u0451\u043d\u043d\u044b\u0435 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442\u043e\u043c')),
                ('user_led', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.User', verbose_name='\u041f\u0440\u0438\u0433\u043b\u0430\u0441\u0438\u0432\u0448\u0438\u0439 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442')),
            ],
            options={
                'ordering': ['-registered_date'],
                'verbose_name': '\u041a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442',
                'verbose_name_plural': '\u041a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='RefferalConsultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=36, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('first_name', models.CharField(max_length=32, verbose_name='\u0418\u043c\u044f')),
                ('consultant_num', models.CharField(blank=True, max_length=40, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442\u0430')),
                ('url_to_personal_room', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u0432 \u043b\u0438\u0447\u043d\u044b\u0439 \u043a\u0430\u0431\u0438\u043d\u0435\u0442')),
                ('refferal_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u0420\u0435\u0444\u0435\u0440\u0430\u043b\u044c\u043d\u0430\u044f \u0441\u0441\u044b\u043b\u043a\u0430')),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u0414\u0430\u0442\u0430 \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('empty_middle_name', models.BooleanField(default=False, verbose_name='\u041d\u0435\u0442 \u043e\u0442\u0447\u0435\u0441\u0442\u0432\u0430.')),
                ('birthday', models.DateTimeField(verbose_name='\u0414\u0435\u043d\u044c \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f')),
                ('citizenship', models.BooleanField(default=False, verbose_name='\u041d\u0435 \u0433\u0440\u0430\u0436\u0434\u0430\u043d\u0438\u043d \u0420\u0424.')),
                ('passport_data', models.CharField(max_length=26, verbose_name='\u0421\u0435\u0440\u0438\u044f \u0438 \u043d\u043e\u043c\u0435\u0440 \u043f\u0430\u0441\u043f\u043e\u0440\u0442\u0430')),
                ('phone_number', models.CharField(max_length=26, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430')),
                ('city', models.CharField(max_length=50, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u041e\u0431\u043b\u0430\u0441\u0442\u044c')),
                ('street', models.CharField(max_length=50, verbose_name='\u0423\u043b\u0438\u0446\u0430')),
                ('num_home', models.CharField(max_length=5, verbose_name='\u0414\u043e\u043c')),
                ('num_apartment', models.DecimalField(decimal_places=1, max_digits=999, verbose_name='\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u0430')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('status', models.CharField(choices=[('\u041d\u043e\u0432\u044b\u0439', b'\xd0\x9d\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb9'), ('\u0417\u0430\u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0439 \u0410', b'\xd0\x97\xd0\xb0\xd1\x80\xd0\xb5\xd0\xb3\xd0\xb8\xd1\x81\xd1\x82\xd1\x80\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb9 \xd0\x90'), ('\u0417\u0430\u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0439 \u0411', b'\xd0\x97\xd0\xb0\xd1\x80\xd0\xb5\xd0\xb3\xd0\xb8\xd1\x81\xd1\x82\xd1\x80\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb9 \xd0\x91'), ('\u041f\u0443\u0441\u0442\u043e\u0439', b'\xd0\x9f\xd1\x83\xd1\x81\xd1\x82\xd0\xbe\xd0\xb9')], default=b'\xd0\x9d\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb9', max_length=20, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438')),
                ('user_lead', models.ManyToManyField(blank=True, related_name='_refferalconsultant_user_lead_+', to=b'accounts.RefferalConsultant', verbose_name='\u041f\u0440\u0438\u0433\u043b\u0430\u0448\u0451\u043d\u043d\u044b\u0435 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442\u043e\u043c')),
                ('user_lead_2', models.ManyToManyField(blank=True, related_name='consultants_of_refferal_consultant', to=b'accounts.User', verbose_name='\u041f\u0440\u0438\u0433\u043b\u0430\u0448\u0451\u043d\u043d\u044b\u0435 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442\u043e\u043c(\u041e\u0431\u044b\u0447\u043d\u044b\u0435)')),
                ('user_led', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.RefferalConsultant', verbose_name='\u041f\u0440\u0438\u0433\u043b\u0430\u0441\u0438\u0432\u0448\u0438\u0439 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442')),
                ('user_led_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.User', verbose_name='\u041f\u0440\u0438\u0433\u043b\u0430\u0441\u0438\u0432\u0448\u0438\u0439 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442(\u041e\u0431\u044b\u0447\u043d\u044b\u0439)')),
            ],
            options={
                'verbose_name': '\u0420\u0435\u0444\u0435\u0440\u0430\u043b\u044c\u043d\u044b\u0439 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442',
                'verbose_name_plural': '\u0420\u0435\u0444\u0435\u0440\u0430\u043b\u044c\u043d\u044b\u0435 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='RefferalConsultantTableRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=36, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('first_name', models.CharField(max_length=32, verbose_name='\u0418\u043c\u044f')),
                ('consultant_num', models.CharField(blank=True, max_length=40, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442\u0430')),
                ('url_to_personal_room', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u0432 \u043b\u0438\u0447\u043d\u044b\u0439 \u043a\u0430\u0431\u0438\u043d\u0435\u0442')),
                ('refferal_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u0420\u0435\u0444\u0435\u0440\u0430\u043b\u044c\u043d\u0430\u044f \u0441\u0441\u044b\u043b\u043a\u0430')),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u0414\u0430\u0442\u0430 \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('empty_middle_name', models.BooleanField(default=False, verbose_name='\u041d\u0435\u0442 \u043e\u0442\u0447\u0435\u0441\u0442\u0432\u0430.')),
                ('birthday', models.DateTimeField(verbose_name='\u0414\u0435\u043d\u044c \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f')),
                ('citizenship', models.BooleanField(default=False, verbose_name='\u041d\u0435 \u0433\u0440\u0430\u0436\u0434\u0430\u043d\u0438\u043d \u0420\u0424.')),
                ('passport_data', models.CharField(max_length=26, verbose_name='\u0421\u0435\u0440\u0438\u044f \u0438 \u043d\u043e\u043c\u0435\u0440 \u043f\u0430\u0441\u043f\u043e\u0440\u0442\u0430')),
                ('phone_number', models.CharField(max_length=26, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430')),
                ('city', models.CharField(max_length=50, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u041e\u0431\u043b\u0430\u0441\u0442\u044c')),
                ('street', models.CharField(max_length=50, verbose_name='\u0423\u043b\u0438\u0446\u0430')),
                ('num_home', models.CharField(max_length=5, verbose_name='\u0414\u043e\u043c')),
                ('num_apartment', models.DecimalField(decimal_places=1, max_digits=999, verbose_name='\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u0430')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('status', models.CharField(choices=[('\u041d\u043e\u0432\u044b\u0439', b'\xd0\x9d\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb9'), ('\u0417\u0430\u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0439 \u0410', b'\xd0\x97\xd0\xb0\xd1\x80\xd0\xb5\xd0\xb3\xd0\xb8\xd1\x81\xd1\x82\xd1\x80\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb9 \xd0\x90'), ('\u0417\u0430\u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0439 \u0411', b'\xd0\x97\xd0\xb0\xd1\x80\xd0\xb5\xd0\xb3\xd0\xb8\xd1\x81\xd1\x82\xd1\x80\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb9 \xd0\x91'), ('\u041f\u0443\u0441\u0442\u043e\u0439', b'\xd0\x9f\xd1\x83\xd1\x81\xd1\x82\xd0\xbe\xd0\xb9')], default=b'\xd0\x9d\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb9', max_length=20, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438')),
                ('user_lead', models.ManyToManyField(blank=True, related_name='_refferalconsultanttablerelations_user_lead_+', to=b'accounts.RefferalConsultantTableRelations', verbose_name='\u041f\u0440\u0438\u0433\u043b\u0430\u0448\u0451\u043d\u043d\u044b\u0435 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442\u043e\u043c')),
                ('user_led', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.RefferalConsultantTableRelations', verbose_name='\u041f\u0440\u0438\u0433\u043b\u0430\u0441\u0438\u0432\u0448\u0438\u0439 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442')),
            ],
            options={
                'verbose_name': 'Consultant',
            },
        ),
        migrations.CreateModel(
            name='RelatedConsultantTableRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=36, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('first_name', models.CharField(max_length=32, verbose_name='\u0418\u043c\u044f')),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('consultant_num', models.CharField(blank=True, max_length=40, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442\u0430')),
                ('url_to_personal_room', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u0432 \u043b\u0438\u0447\u043d\u044b\u0439 \u043a\u0430\u0431\u0438\u043d\u0435\u0442')),
                ('refferal_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u0420\u0435\u0444\u0435\u0440\u0430\u043b\u044c\u043d\u0430\u044f \u0441\u0441\u044b\u043b\u043a\u0430')),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u0414\u0430\u0442\u0430 \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438')),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-registered_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelatedConsultant',
            fields=[
                ('relatedconsultanttablerelations_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.RelatedConsultantTableRelations')),
            ],
            options={
                'verbose_name': '\u0421\u0442\u043e\u0440\u043e\u043d\u043d\u0438\u0439 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442',
                'verbose_name_plural': '\u0421\u0442\u043e\u0440\u043e\u043d\u043d\u0438\u0439 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442\u044b',
            },
            bases=('accounts.relatedconsultanttablerelations',),
        ),
        migrations.AddField(
            model_name='relatedconsultanttablerelations',
            name='user_lead',
            field=models.ManyToManyField(blank=True, related_name='_relatedconsultanttablerelations_user_lead_+', to=b'accounts.RelatedConsultantTableRelations', verbose_name='\u041f\u0440\u0438\u0433\u043b\u0430\u0448\u0451\u043d\u043d\u044b\u0435 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442\u043e\u043c'),
        ),
        migrations.AddField(
            model_name='relatedconsultanttablerelations',
            name='user_led',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.RelatedConsultantTableRelations', verbose_name='\u041f\u0440\u0438\u0433\u043b\u0430\u0441\u0438\u0432\u0448\u0438\u0439 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_lead_1',
            field=models.ManyToManyField(blank=True, related_name='related_consultants_of_consultant', to=b'accounts.RelatedConsultantTableRelations', verbose_name='\u041f\u0440\u0438\u0433\u043b\u0430\u0448\u0451\u043d\u043d\u044b\u0435 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442\u043e\u043c(\u0421\u0442\u043e\u0440\u043e\u043d\u043d\u0438\u0435)'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_lead_2',
            field=models.ManyToManyField(blank=True, related_name='refferal_consultants_of_consultant', to=b'accounts.RefferalConsultantTableRelations', verbose_name='\u041f\u0440\u0438\u0433\u043b\u0430\u0448\u0451\u043d\u043d\u044b\u0435 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442\u043e\u043c(\u0420\u0435\u0444\u0435\u0440\u0430\u043b\u044c\u043d\u044b\u0435)'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_led_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.RelatedConsultantTableRelations', verbose_name='\u041f\u0440\u0438\u0433\u043b\u0430\u0441\u0438\u0432\u0448\u0438\u0439 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442(\u0421\u0442\u043e\u0440\u043e\u043d\u043d\u0438\u0439)'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_led_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.RefferalConsultantTableRelations', verbose_name='\u041f\u0440\u0438\u0433\u043b\u0430\u0441\u0438\u0432\u0448\u0438\u0439 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442(\u0420\u0435\u0444\u0435\u0440\u0430\u043b\u044c\u043d\u044b\u0439)'),
        ),
        migrations.AddField(
            model_name='relatedconsultant',
            name='user_lead_1',
            field=models.ManyToManyField(blank=True, related_name='consultants_of_related_consultant', to=b'accounts.User', verbose_name='\u041f\u0440\u0438\u0433\u043b\u0430\u0448\u0451\u043d\u043d\u044b\u0435 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442\u043e\u043c(\u041e\u0431\u044b\u0447\u043d\u044b\u0435)'),
        ),
        migrations.AddField(
            model_name='relatedconsultant',
            name='user_lead_2',
            field=models.ManyToManyField(blank=True, related_name='refferal_consultants_of_related_consultant', to=b'accounts.RefferalConsultantTableRelations', verbose_name='\u041f\u0440\u0438\u0433\u043b\u0430\u0448\u0451\u043d\u043d\u044b\u0435 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442\u043e\u043c(\u0420\u0435\u0444\u0435\u0440\u0430\u043b\u044c\u043d\u044b\u0435)'),
        ),
        migrations.AddField(
            model_name='relatedconsultant',
            name='user_led_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.User', verbose_name='\u041f\u0440\u0438\u0433\u043b\u0430\u0441\u0438\u0432\u0448\u0438\u0439 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442(\u041e\u0431\u044b\u0447\u043d\u044b\u0439)'),
        ),
        migrations.AddField(
            model_name='relatedconsultant',
            name='user_led_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.RefferalConsultantTableRelations', verbose_name='\u041f\u0440\u0438\u0433\u043b\u0430\u0441\u0438\u0432\u0448\u0438\u0439 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442(\u0420\u0435\u0444\u0435\u0440\u0430\u043b\u044c\u043d\u044b\u0439)'),
        ),
        migrations.AddField(
            model_name='refferalconsultant',
            name='user_lead_1',
            field=models.ManyToManyField(blank=True, related_name='consultants_of_refferal_consultant', to=b'accounts.RelatedConsultant', verbose_name='\u041f\u0440\u0438\u0433\u043b\u0430\u0448\u0451\u043d\u043d\u044b\u0435 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442\u043e\u043c(\u0421\u0442\u043e\u0440\u043e\u043d\u043d\u0438\u0435)'),
        ),
        migrations.AddField(
            model_name='refferalconsultant',
            name='user_led_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.RelatedConsultant', verbose_name='\u041f\u0440\u0438\u0433\u043b\u0430\u0441\u0438\u0432\u0448\u0438\u0439 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442(\u0421\u0442\u043e\u0440\u043e\u043d\u043d\u0438\u0439)'),
        ),
        migrations.AddField(
            model_name='relatedconsultanttablerelations',
            name='empty_middle_name',
            field=models.BooleanField(default=False, verbose_name='\u041d\u0435\u0442 \u043e\u0442\u0447\u0435\u0441\u0442\u0432\u0430.'),
        ),
    ]
