# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_squashed_0004_relatedconsultanttablerelations_empty_middle_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '\u041a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442', 'verbose_name_plural': '\u041a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442\u044b'},
        ),
        migrations.AlterField(
            model_name='refferalconsultant',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='refferalconsultanttablerelations',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
    ]
