# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171204_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedconsultanttablerelations',
            name='status',
            field=models.CharField(choices=[('\u041d\u043e\u0432\u044b\u0439', b'\xd0\x9d\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb9'), ('\u0417\u0430\u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0439 \u0410', b'\xd0\x97\xd0\xb0\xd1\x80\xd0\xb5\xd0\xb3\xd0\xb8\xd1\x81\xd1\x82\xd1\x80\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb9 \xd0\x90'), ('\u0417\u0430\u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0439 \u0411', b'\xd0\x97\xd0\xb0\xd1\x80\xd0\xb5\xd0\xb3\xd0\xb8\xd1\x81\xd1\x82\xd1\x80\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb9 \xd0\x91'), ('\u041f\u0443\u0441\u0442\u043e\u0439', b'\xd0\x9f\xd1\x83\xd1\x81\xd1\x82\xd0\xbe\xd0\xb9')], default=b'\xd0\x9d\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb9', max_length=20, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='refferalconsultant',
            name='citizenship',
            field=models.BooleanField(default=False, verbose_name='\u041d\u0435 \u0433\u0440\u0430\u0436\u0434\u0430\u043d\u0438\u043d \u0420\u0424'),
        ),
        migrations.AlterField(
            model_name='refferalconsultanttablerelations',
            name='citizenship',
            field=models.BooleanField(default=False, verbose_name='\u041d\u0435 \u0433\u0440\u0430\u0436\u0434\u0430\u043d\u0438\u043d \u0420\u0424'),
        ),
        migrations.AlterField(
            model_name='user',
            name='citizenship',
            field=models.BooleanField(default=False, verbose_name='\u041d\u0435 \u0433\u0440\u0430\u0436\u0434\u0430\u043d\u0438\u043d \u0420\u0424'),
        ),
    ]
