# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-27 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180314_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='refferalconsultant',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u041f\u043e\u0441\u043b\u0435\u0434\u043d\u044f\u044f \u0430\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u044c \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442\u0430'),
        ),
        migrations.AddField(
            model_name='refferalconsultant',
            name='password',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='\u041f\u0430\u0440\u043e\u043b\u044c \u043e\u0442 \u0430\u043a\u043a\u0430\u0443\u043d\u0442\u0430'),
        ),
        migrations.AddField(
            model_name='refferalconsultanttablerelations',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u041f\u043e\u0441\u043b\u0435\u0434\u043d\u044f\u044f \u0430\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u044c \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442\u0430'),
        ),
        migrations.AddField(
            model_name='refferalconsultanttablerelations',
            name='password',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='\u041f\u0430\u0440\u043e\u043b\u044c \u043e\u0442 \u0430\u043a\u043a\u0430\u0443\u043d\u0442\u0430'),
        ),
        migrations.AddField(
            model_name='relatedconsultanttablerelations',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u041f\u043e\u0441\u043b\u0435\u0434\u043d\u044f\u044f \u0430\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u044c \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442\u0430'),
        ),
        migrations.AddField(
            model_name='relatedconsultanttablerelations',
            name='password',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='\u041f\u0430\u0440\u043e\u043b\u044c \u043e\u0442 \u0430\u043a\u043a\u0430\u0443\u043d\u0442\u0430'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u041f\u043e\u0441\u043b\u0435\u0434\u043d\u044f\u044f \u0430\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u044c \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u043d\u0442\u0430'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='\u041f\u0430\u0440\u043e\u043b\u044c \u043e\u0442 \u0430\u043a\u043a\u0430\u0443\u043d\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='refferalconsultant',
            name='city',
            field=models.CharField(max_length=50, verbose_name='\u0413\u043e\u0440\u043e\u0434, \u041e\u0431\u043b\u0430\u0441\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='refferalconsultanttablerelations',
            name='city',
            field=models.CharField(max_length=50, verbose_name='\u0413\u043e\u0440\u043e\u0434, \u041e\u0431\u043b\u0430\u0441\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=50, verbose_name='\u0413\u043e\u0440\u043e\u0434, \u041e\u0431\u043b\u0430\u0441\u0442\u044c'),
        ),
    ]
