# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-08 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('utm_content', models.CharField(blank=True, default=b'', max_length=200, null=True, verbose_name='\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u0430\u044f \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f, \u043a\u043e\u0442\u043e\u0440\u0430\u044f \u043f\u043e\u043c\u043e\u0433\u0430\u0435\u0442 \u0440\u0430\u0437\u043b\u0438\u0447\u0430\u0442\u044c \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u044f;')),
                ('utm_source', models.CharField(default=b'', max_length=200, verbose_name='\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a \u043f\u0435\u0440\u0435\u0445\u043e\u0434\u0430')),
                ('utm_campaign', models.CharField(default=b'', max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0440\u0435\u043a\u043b\u0430\u043c\u043d\u043e\u0439 \u043a\u0430\u043c\u043f\u0430\u043d\u0438\u0438')),
                ('utm_medium', models.CharField(blank=True, default=b'', max_length=200, null=True, verbose_name='\u0422\u0438\u043f \u0442\u0440\u0430\u0444\u0438\u043a\u0430')),
                ('utm_term', models.CharField(default=b'', max_length=200, verbose_name='\u0422\u0438\u043f \u0442\u0440\u0430\u0444\u0438\u043a\u0430')),
            ],
            options={
                'db_table': 'cosmeticsyou_advertising_utm_marks',
                'verbose_name': 'UTM \u041c\u0435\u0442\u043a\u0430',
                'verbose_name_plural': 'UTM \u041c\u0435\u0442\u043a\u0438',
            },
        ),
    ]
